CREATE TABLE stakeholders (
	id UUID PRIMARY KEY,
	tenant_id VARCHAR(255) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	role VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
